version: '3.0'
services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '8002:8002'
    depends_on:
      - mysql
    volumes:
      - './:/app'
    entrypoint: ["dockerize", "-wait", "tcp://mysql:3306", "-timeout", "20s"]
    command: ["python", "manage.py", "runserver", "0.0.0.0:8002"]

  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - ./mysql:/var/lib/mysql/
    environment:
        MYSQL_DATABASE: "payhere"
        MYSQL_USER: "root"
        MYSQL_ROOT_PASSWORD: "asdf1234"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    ports:
      - "3306:3306"
    expose:
      - '3306'